image: alpine:3.13 # latest in 20210515

definitions:
  steps:
    build: &build
      name: Build
      image: node:12-alpine
      script:
        - apk add gettext
        - envsubst < .env.deployment > .env
        - yarn
        - yarn build
      artifacts:
        - build/**

    deploy: &deploy
      name: Deploy to S3
      script:
        - pipe: atlassian/aws-s3-deploy:0.2.4
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            S3_BUCKET: $S3_BUCKET_NAME
            ACL: $S3_ACL
            LOCAL_PATH: "build"
            WAIT: "true"

    invalidate: &invalidate
      name: Invalidate Cloudfront Cache
      script:
        - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            DISTRIBUTION_ID: $DISTRIBUTION_ID

pipelines:
  branches:
    develop:
      - step:
          <<: *build
          deployment: DevelopBuild
      - step:
          <<: *deploy
          deployment: DevelopDeploy
      - step:
          <<: *invalidate
          deployment: DevelopInvalidateCloudfront
    staging:
      - step:
          <<: *build
          deployment: StagingBuild
      - step:
          <<: *deploy
          deployment: StagingDeploy
      - step:
          <<: *invalidate
          deployment: StagingInvalidateCloudfront